### ISSUE TITLE
Allow disabling of public signup

### ISSUE THREAD

**Issue by pietvanzoen** [pietvanzoen/gifable#40]
- [x] Setup env for disabling public signup
- [ ] Add admin form for creating users

**Comment by jason-weiser** [comment]
Thank you so much for making such an awesome service. It's exactly what I'm looking for to host my own gifs. 

I would like to throw a vote behind this feature. As much as I would love to host this, it's currently impossible to be able to share gifs on the internet as well as keep people from uploading their own images to my server.

Anyway, again, awesome app, and thanks so much for your work and for sharing.

**Comment by pietvanzoen** [comment]
Thanks for the kind words @jason-weiser. :)

I just merged #101. Let me know if that works for you.

I also added https://github.com/pietvanzoen/gifable/issues/102. I'll try to get to that this week.
